name: Build and Run
on:
  workflow_dispatch:
  schedule:
    - cron:  "0 0 * * *"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3.0.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Run
        run: java -jar target/SlimefunScrapper.jar

      - name: Checkout (Post-Build)
        uses: actions/checkout@v3.0.0

      - name: Push
        run: |
          git config --global user.name 'PushBot'
          git config --global user.email 'thesilentpro@users.noreply.github.com'
          git commit -m 'Auto push changes' /home/runner/work/SlimefunScrapper/SlimefunScrapper/items.json
          git push